name: Build and Deploy Web App
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: 1023c04-grupo4
      DIST: dist  # La carpeta por defecto de salida para proyectos Vue.js
      REGION: us-east-1
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Project
        run: |
          npm run build

      - name: Check if the build directory exists
        run: test -d $DIST
        continue-on-error: true

      - name: Copy files to the production website with the AWS CLI
        run: |
          if [ -d $DIST ]; then
            aws s3 sync $DIST s3://${{ env.BUCKET }}
          else
            echo "Error: The '$DIST' directory does not exist."
            exit 1
          fi
